name: Create release

on: [workflow_dispatch]

permissions: write-all

jobs:
  compile-ubuntu:
    uses: ./.github/workflows/ubuntu-18.04-compile.yml
    secrets: inherit

  create-release:
    needs: compile-ubuntu
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v3

      - name: Read Changelog.md and use it as a body of new release
        id: read_release
        shell: bash
        run: |
          r=$(cat Changelog.md)
          r="${r//'%'/'%25'}"
          r="${r//$'\n'/'%0A'}"
          r="${r//$'\r'/'%0D'}"
          echo "::set-output name=CHANGELOG_BODY::$r"

      - name: Get current date
        id: date
        run: echo "::set-output name=date::$(date +'%Y.%m')"

      - name: Get registration token
        id: getRegToken
        run: |
          curl -X POST -H \"Accept: application/vnd.github+json\"  -H 'Authorization: token ${{ secrets.GITHUB_TOKEN }}' https://api.github.com/repos/neodix42/HardTestDevelopment/actions/runners/registration-token

      - name: Create release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: v${{ steps.date.outputs.date }}
          release_name: v${{ steps.date.outputs.date }}
          body: |
            ${{ steps.read_release.outputs.CHANGELOG_BODY }}
          draft: false
          prerelease: false

      - name: Upload artifacts
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: artifacts/fift
          asset_name: ubuntus
          tag: v${{ steps.date.outputs.date }}
          overwrite: true